In [2]:
import pandas as pd
import statsmodels.api as sm

In [3]:
df = pd.read_csv('/Users/weihsi/Dropbox/Thinkful/thinkful_hello/Linear Regression/loansData_clean.csv')

In [4]:
df['Interest.Check'] = df['Interest.Rate'].map(lambda x: x < 0.12 )

In [5]:
df.head(5)

,Amount.Requested,Amount.Funded.By.Investors,Interest.Rate,Loan.Length,Loan.Purpose,Debt.To.Income.Ratio,State,Home.Ownership,Monthly.Income,FICO.Range,Open.CREDIT.Lines,Revolving.CREDIT.Balance,Inquiries.in.the.Last.6.Months,Employment.Length,FICO.Score,Interest.Check
0,20000,20000,0.0890,36,debt_consolidation,14.90%,SC,MORTGAGE,6541.67,735-739,14,14272,2,< 1 year,735,True
1,19200,19200,0.1212,36,debt_consolidation,28.36%,TX,MORTGAGE,4583.33,715-719,12,11140,1,2 years,715,False
2,35000,35000,0.2198,60,debt_consolidation,23.81%,CA,MORTGAGE,11500.00,690-694,14,21977,1,2 years,690,False
3,10000,9975,0.0999,36,debt_consolidation,14.30%,KS,MORTGAGE,3833.33,695-699,10,9346,0,5 years,695,True
4,12000,12000,0.1171,36,credit_card,18.78%,NJ,RENT,3195.00,695-699,11,14469,0,9 years,695,True

In [6]:
df['Const_Intercept'] = 1.0

In [7]:
df.head()

,Amount.Requested,Amount.Funded.By.Investors,Interest.Rate,Loan.Length,Loan.Purpose,Debt.To.Income.Ratio,State,Home.Ownership,Monthly.Income,FICO.Range,Open.CREDIT.Lines,Revolving.CREDIT.Balance,Inquiries.in.the.Last.6.Months,Employment.Length,FICO.Score,Interest.Check,Const_Intercept
0,20000,20000,0.0890,36,debt_consolidation,14.90%,SC,MORTGAGE,6541.67,735-739,14,14272,2,< 1 year,735,True,1
1,19200,19200,0.1212,36,debt_consolidation,28.36%,TX,MORTGAGE,4583.33,715-719,12,11140,1,2 years,715,False,1
2,35000,35000,0.2198,60,debt_consolidation,23.81%,CA,MORTGAGE,11500.00,690-694,14,21977,1,2 years,690,False,1
3,10000,9975,0.0999,36,debt_consolidation,14.30%,KS,MORTGAGE,3833.33,695-699,10,9346,0,5 years,695,True,1
4,12000,12000,0.1171,36,credit_card,18.78%,NJ,RENT,3195.00,695-699,11,14469,0,9 years,695,True,1

In [1]:
ind_vars = ['FICO.score', 'Amount.Requested', 'Const_Intercept']