In [46]:
import pandas as pd
import statsmodels.api as sm
import math

In [24]:
df = pd.read_csv('/Users/weihsi/Dropbox/Thinkful/thinkful_hello/Linear Regression/loansData_clean.csv')

In [25]:
df['IR_TF'] = df['Interest.Rate'].map(lambda x: x < 0.12 )

In [26]:
df.head(5)

,Amount.Requested,Amount.Funded.By.Investors,Interest.Rate,Loan.Length,Loan.Purpose,Debt.To.Income.Ratio,State,Home.Ownership,Monthly.Income,FICO.Range,Open.CREDIT.Lines,Revolving.CREDIT.Balance,Inquiries.in.the.Last.6.Months,Employment.Length,FICO.Score,IR_TF
0,20000,20000,0.0890,36,debt_consolidation,14.90%,SC,MORTGAGE,6541.67,735-739,14,14272,2,< 1 year,735,True
1,19200,19200,0.1212,36,debt_consolidation,28.36%,TX,MORTGAGE,4583.33,715-719,12,11140,1,2 years,715,False
2,35000,35000,0.2198,60,debt_consolidation,23.81%,CA,MORTGAGE,11500.00,690-694,14,21977,1,2 years,690,False
3,10000,9975,0.0999,36,debt_consolidation,14.30%,KS,MORTGAGE,3833.33,695-699,10,9346,0,5 years,695,True
4,12000,12000,0.1171,36,credit_card,18.78%,NJ,RENT,3195.00,695-699,11,14469,0,9 years,695,True

In [27]:
df = sm.add_constant(df, prepend = True)

In [58]:
df.head(10)

,const,Amount.Requested,Amount.Funded.By.Investors,Interest.Rate,Loan.Length,Loan.Purpose,Debt.To.Income.Ratio,State,Home.Ownership,Monthly.Income,FICO.Range,Open.CREDIT.Lines,Revolving.CREDIT.Balance,Inquiries.in.the.Last.6.Months,Employment.Length,FICO.Score,IR_TF
0,1,20000,20000,0.0890,36,debt_consolidation,14.90%,SC,MORTGAGE,6541.67,735-739,14,14272,2,< 1 year,735,True
1,1,19200,19200,0.1212,36,debt_consolidation,28.36%,TX,MORTGAGE,4583.33,715-719,12,11140,1,2 years,715,False
2,1,35000,35000,0.2198,60,debt_consolidation,23.81%,CA,MORTGAGE,11500.00,690-694,14,21977,1,2 years,690,False
3,1,10000,9975,0.0999,36,debt_consolidation,14.30%,KS,MORTGAGE,3833.33,695-699,10,9346,0,5 years,695,True
4,1,12000,12000,0.1171,36,credit_card,18.78%,NJ,RENT,3195.00,695-699,11,14469,0,9 years,695,True
5,1,6000,6000,0.1531,36,other,20.05%,CT,OWN,4891.67,670-674,17,10391,2,3 years,670,False
6,1,10000,10000,0.0790,36,debt_consolidation,26.09%,MA,RENT,2916.67,720-724,10,15957,0,10+ years,720,True
7,1,33500,33450,0.1714,60,credit_card,14.70%,LA,MORTGAGE,13863.42,705-709,12,27874,0,10+ years,705,False
8,1,14675,14675,0.1433,36,credit_card,26.92%,CA,RENT,3150.00,685-689,9,7246,1,8 years,685,False
9,1,7000,7000,0.0691,36,credit_card,7.10%,CA,RENT,5000.00,715-719,8,7612,0,3 years,715,True

In [34]:
ind_vars = ['FICO.Score', 'Amount.Requested', 'const']

In [35]:
logit = sm.Logit(df['IR_TF'], df[ind_vars])

In [36]:
result = logit.fit()

Optimization terminated successfully.
         Current function value: 0.319503
         Iterations 8

In [41]:
coeff = result.params
print result.summary()

                           Logit Regression Results
==============================================================================
Dep. Variable:                  IR_TF   No. Observations:                 2500
Model:                          Logit   Df Residuals:                     2497
Method:                           MLE   Df Model:                            2
Date:                Tue, 28 Apr 2015   Pseudo R-squ.:                  0.5243
Time:                        00:04:26   Log-Likelihood:                -798.76
converged:                       True   LL-Null:                       -1679.2
                                        LLR p-value:                     0.000
====================================================================================
                       coef    std err          z      P>|z|      [95.0% Conf. Int.]
------------------------------------------------------------------------------------
FICO.Score           0.0874      0.004     24.779      0.000         0.081     0.094
Amount.Requested    -0.0002    1.1e-05    -15.815      0.000        -0.000    -0.000
const              -60.1250      2.420    -24.840      0.000       -64.869   -55.381
====================================================================================

In [56]:
def logistic_function(FICO_Score, Loan_Amt):
    p = 1/(1 + math.e**(-60.125045 + 0.087423*(FICO_Score) - 0.000174*(Loan_Amt)))
    return p

In [61]:
logistic_function(720, 10000)

0.2535978093816657